version: "3.9"

services:
  rakaiseto:
    networks:
      - rakaiseto-com-network
    image: ghcr.io/rakaiseto/rakaiseto.com:latest
    container_name: rakaiseto-com
    restart: always
    ports:
      - "127.0.0.1:21001:8092"
    environment:
      NODE_ENV: production
      PORT: 8092
      HOST: "0.0.0.0"
networks:
  rakaiseto-com-network: